apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonLabels:
  app.kubernetes.io/name: sri-demo-be
  app.kubernetes.io/instance: production

resources:
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

# Uncomment untuk patch image tag
images:
- name: ghcr.io/danielyericho/sri_demo_registry
  newTag: be-latest
  newName: ghcr.io/danielyericho/sri_demo_registry

# Uncomment untuk environment-specific configuration
# vars:
# - name: APP_ENV
#   value: production
